konveyor/kantra

Dockerfile, cmd/analyze.go
=> :sparkles: add rulesets, shim, use analyzer base image as the final layer

Dockerfile, cmd/analyze.go, cmd/root.go, cmd/settings.go, main.go, settings.json
Closes #3 
Closes #4 
Closes #5 
Closes #6 
Closes #10
=> Use analyzer input and output

Dockerfile, cmd/settings.go, cmd/shimconvert.go, cmd/transform.go
=> Shim convert for transform subcommand

.github/workflows/testing.yaml, cmd/analyze.go, cmd/container.go, cmd/openrewrite.go, cmd/root.go, cmd/settings.go, cmd/shimconvert.go, cmd/transform.go, test-data/analysis-output.yaml
=> :sparkles: use context-lines option

test-data/analysis-output.yaml, test-data/deps-output.yaml
Fixing `konveyor-jdt` scheme to `file://` scheme
=> :bug: fixing ci with latest analyzer-lsp

cmd/analyze.go
=> MTA-1294: Display link to static report

cmd/settings.go
Fixes #107 
As discussed [via Slack](https://kubernetes.slack.com/archives/C04QZJFQ0UA/p1698853574068369?thread_ts=1698830510.500689&cid=C04QZJFQ0UA)
=> :bug: Ensure that env variable PODMAN_BIN wins

Dockerfile, cmd/analyze.go, cmd/settings.go
=> Add --enable-default-rulesets flag

cmd/analyze.go, cmd/settings.go, hack/update-settings.sh
This is needed so the bundle name can be replaced based on what image we are building
=> :ghost: Make bundles location a config setting

cmd/analyze.go
=> MTA-2064: Fix duplicate sources/targets

OWNERS.md
=> Add OWNERS.md

Dockerfile, cmd/openrewrite.go, openrewrite_entrypoint.sh
Resolves https://issues.redhat.com/browse/MTA-2332
=> Copy openrewrite source from mount to container

Dockerfile, cmd/openrewrite.go, openrewrite_entrypoint.sh
copy openrewrite source from mount to container
=> Copy openrewrite source from mount to container (#173)

.github/workflows/multi-arch-image-build.yaml, .github/workflows/testing.yaml, Dockerfile, cmd/analyze.go, pkg/container/container.go, test-data/analysis-output.yaml, test-data/deps-output.yaml
Fixes #177 
Fixes #208 
This reverts back the pinned rulesets to use the latest thing and also fixes the volume mount issue.
=> :bug: fix volumes in shared containers, update demo output for new rulesets

README.md
- Update command to download correct binary for mac/windows instead linux.
=> Update Mac/windows installation command

cmd/analyze.go
Fixes https://issues.redhat.com/browse/MTA-2820
=> Fix removing provider container error

cmd/analyze.go
=> Do not run cleanup for list options

cmd/analyze.go
Also removing duplicate input validation code.
fixes #239
=> :bug: Moving clean-up of resource to after the resources are created.

cmd/analyze.go
Updating static-report generator parameters to not include not existing depdendencies.yaml files for single input as well as --bulk inputs.
=> :bug: Skip missing dependencies files

cmd/analyze.go
Closes #236 
Closes #255 
Closes #267
=> Fix static report URL, validate files, set NodeJS provider

cmd/analyze.go
=> Use Alizer to only detect languages

cmd/analyze.go
=> Help description for full analysis mode

cmd/analyze.go
addresses https://issues.redhat.com/browse/MTA-3290
=> Use builtin provider only

cmd/analyze.go
Fixes https://issues.redhat.com/browse/MTA-3289
=> Fix deps output on static report

cmd/analyze.go
=> :bug: clean up resource's even if analysis fails

cmd/analyze.go
This addresses a bug where custom rules were not being passed correctly.
=> :bug: Handle custom rules for .net framework

cmd/analyze.go, cmd/cleanup.go, pkg/container/container.go
Closes https://issues.redhat.com/browse/MTA-3133
=> Include more detailed container names

cmd/analyze.go
Fixes https://issues.redhat.com/browse/MTA-3700
=> Generate static report if no deps output

cmd/analyze.go
Fixes https://issues.redhat.com/browse/MTA-3668
=> Fallback for detecting java projects

cmd/analyze-bin.go, cmd/analyze.go, cmd/cleanup.go, cmd/root.go, cmd/settings.go
Relies on env variable `RUN_LOCAL` to determine running analysis in containers or containerless.
Resolves https://issues.redhat.com/browse/MTA-4012 
Fixes https://issues.redhat.com/browse/MTA-3624
=> Containerless option under analyze cmd

cmd/analyze.go, go.mod, go.sum
Fixes https://issues.redhat.com/browse/MTA-4159
Fixes https://issues.redhat.com/browse/MTA-4280
=> Update java provider & fix --list-providers

cmd/analyze-bin.go, go.mod, go.sum
Fixes https://issues.redhat.com/browse/MTA-4484
=> Remove exploded java dirs

cmd/analyze.go, cmd/java.go, cmd/openrewrite.go, cmd/shimconvert.go
Fixes https://issues.redhat.com/browse/MTA-4553
=> Fix openrewrite mount mvn settings

cmd/analyze-bin.go, go.mod, go.sum
=> CP #422: Remove exploded java dirs 

cmd/analyze.go, cmd/openrewrite.go, cmd/shimconvert.go
openrewrite mount mvn settings
=> CP #421: Fix openrewrite mount mvn settings 

go.mod, go.sum
Resolves https://issues.redhat.com/browse/MTA-4636
=> Update Java provider for windows dep URI

cmd/static-report.go
Adding updated static-report change populating Issue description field with Message to container-less analysis.
Related to https://github.com/konveyor/kantra/issues/341
=> :bug: Update Issue Description for containerless

cmd/analyze-bin.go, cmd/shimconvert.go
Fixes https://issues.redhat.com/browse/MTA-4772
=> Convert xml rule files

cmd/asset_generation/discover/cloud_foundry/discover_test.go, docs/examples.md, go.mod, go.sum
Fixes missing memory key, value pair in discover manifest issue
Signed-off-by: Gloria Ciavarrini <gciavarrini@redhat.com>
=> Update asset generation library

cmd/asset_generation/discover/cloud_foundry/discover_test.go, go.mod, go.sum
=> Update asset generation lib version

cmd/analyze.go, cmd/internal/hiddenfile/hidden_unix.go, cmd/internal/hiddenfile/hidden_windows.go
Resolves https://issues.redhat.com/browse/MTA-5207
=> :bug: improve handling of hidden files
