Dockerfile
cmd/analyze.go

Convert xml rules to yaml for analyze

---

cmd/analyze.go
cmd/container.go
cmd/shimconvert.go
test-data/analysis-output.yaml

Fix commands for windows

---

cmd/analyze.go

Add JSON output option

---

.github/workflows/testing.yaml

In our current script, we compare the full output which contains skipped and unmatched rules. This list changes everytime there are updates to rulesets. With this PR, we will only check if there's diffeerences in created issues and tags and nothing else.

:ghost: improve CI

---

cmd/analyze.go
cmd/openrewrite.go
cmd/root.go
cmd/shimconvert.go

Fixes #92 
Fixes #55
* Disables analysis logs to stdout 
* Passes down log level to analyzer command
* Adds log files for all commands and prints logs there
* Replaces deprecated ioutil.WriteFile with os.WriteFile

:bug: Fix no-cleanup option, disable analysis logs to stdout

---

README.md

include podman resource requirements for mac

---

cmd/analyze.go
cmd/root.go
cmd/settings.go
go.mod
go.sum
hack/README.md

Also adds jaeger in case we need to debug.

:sparkles: Share maven cache between analyze and dep, use JVM max setting

---

cmd/analyze.go

MTA-1297: add overwrite option

---

README.md
docs/analyzer.md
docs/developer.md
docs/example.md
docs/usage.md
docs/windup.md

Add docs for analyze and dev

---

hack/darwin_restart_podman_machine.sh

Related to https://github.com/konveyor/kantra/issues/111

🌱 Address too many open files on MacOS

---

Dockerfile
cmd/settings.go

use err for lookpath

---

Dockerfile
cmd/analyze.go
entrypoint.sh
test-data/analysis-output.yaml

Basically the biggest issue with running on Mac and windows is the virtualization layer and file i/o over that virtualization. 
Podman is currently working on this; until that is finished, copying the source to the container to reduce file i/o speeds up the process by quite a bit.
I am seeing 5-minute runs after this change for analyzing `coolstuff-javaee` from 24min with the same output.

:bug: adding entrypoint to copy source from mount to container

---

cmd/analyze.go

Hardcoded `kantra` executable path could be different in other build environments, using Settings.RootCommandName to not depend on the kantra name.
Fixes: https://issues.redhat.com/browse/MTA-1998

:bug: Use RootCommandName for labels lookup

---

.github/workflows/multi-arch-image-build.yaml
Dockerfile

This forces us to build the base images we require (ie. windup-shim, static-report, and analyzer-lsp) before building our kantra image.

:seedling: require base images

---

cmd/analyze.go

Backport of https://github.com/konveyor/kantra/pull/138
Use RootCommandName for labels lookup
Hardcoded `kantra` executable path could be different in other build environments, using Settings.RootCommandName to not depend on kantra name.
Fixes: https://issues.redhat.com/browse/MTA-1998

[backport] :bug: Use RootCommandName for labels lookup (#138)

---

cmd/analyze.go

Adding `proxy` command line option to specify proxy string as an argument. THe proxy s passed to analyzer providers settings.
Fixes: https://github.com/konveyor/kantra/issues/11

:sparkles: Add proxy option

---

README.md
cmd/openrewrite.go

Maven settings.xml file can be now specified as parameter for kantra transform openrewrite command (that uses maven for its execution).
Fixes: https://github.com/konveyor/kantra/issues/19

:sparkles: Add settings file option to openrewrite

---

.github/workflows/multi-arch-image-build.yaml
Dockerfile
cmd/root.go
cmd/settings.go
cmd/version.go

Adding tool version to CLI that should return version number and commit hash. Usage: `kantra version`.
The version can be setup when building the kantra, example:
```
$ go build --ldflags="-X 'github.com/konveyor-ecosystem/kantra/cmd.Version=1.1.1' -X 'github.com/konveyor-ecosystem/kantra/cmd.BuildCommit=$(git rev-parse HEAD)'"
$ ./kantra version
version: 1.1.1
SHA: 75daa9736c52e85cad832d1cd2eb95d2d98dad8e
```
The default development version `99.0.0` follows operator and [UI convention](https://github.com/konveyor/tackle2-ui/blob/main/common/src/environment.ts#L63).
Fixes: https://issues.redhat.com/browse/MTA-2201

Add version

---

.github/workflows/multi-arch-image-build.yaml

Using github variables to provide version and commit sha variables for build.
Follow-up to https://github.com/konveyor/kantra/pull/154

Fix version variables evaluation in github build

---

.github/workflows/multi-arch-image-build.yaml
Dockerfile
cmd/root.go
cmd/version.go

0.3 backport of https://github.com/konveyor/kantra/pull/154 and https://github.com/konveyor/kantra/pull/156

[BACKPORT] Add version 

---

cmd/analyze.go
test-data/deps-output.yaml

fixes https://github.com/konveyor/analyzer-lsp/issues/529

:bug: remove dependency only pod, use new dep-output flag to get dependencies

---

cmd/analyze.go
cmd/openrewrite.go
cmd/shimconvert.go
pkg/container/container.go

Override container runtime for commands

---

.github/workflows/testing.yaml
cmd/analyze.go
entrypoint.sh
pkg/testing/runner.go

:bug: fixing the location of the created programs to correct dir 

---

README.md

Fix a few minor issues I spotted in README.md:
* Fix indentation for OS-specific instructions. The indent has to be past the `1. `, so two spaces wasn't enough. Later in the doc, four spaces are used, so use that here too. (Three would also work, but doesn't look nice in some editors.)
* Grammar--perhaps opinion.
* `sucommand` typo.
If someone has larger changes in the works, please feel free to ignore this PR to avoid merge conflicts. 🙂

Fix minor README.md issues

---

README.md
test-data/deps-output.yaml

This PR addresses issues with the dependency test in the GitHub Actions workflow by updating the deps-output.yaml file. The changes ensure that the generated output file aligns correctly with the test file for accurate comparison.
This new structure of YAML is introduced in the dependent PR of analyzer-LSP: https://github.com/konveyor/analyzer-lsp/pull/566

Fix dependency test: update deps-output.yaml test output file.

---

cmd/analyze.go
cmd/test.go
pkg/testing/runner.go

I think there's a bug in test runner when running in parallel. I am making it all serial for the moment, will look into it later when I get the time.

:bug: update java provider settings + serialize test runner

---

cmd/analyze.go

:sparkles: add --incident-selector and --context-lines

---

.github/workflows/testing.yaml

This adds a new job to test already published images based on a tag. The idea is to run this as a nightly test. I will follow up with that workflow as this needs to be merged first to test.

:ghost: add a job to test published images

---

cmd/analyze.go

Add NodeJS and Python providers

---

cmd/analyze.go

Adding validation for analysis source and target labels.
Fixes: https://github.com/konveyor/kantra/issues/176

:bug: Validate source and target labels

---

cmd/analyze.go
cmd/settings.go
cmd/settings_test.go

Fixing fmt.Fprintln to correctly recognize first argument as a writer buffer. Bug was introduced in my PR https://github.com/konveyor/kantra/pull/243
This should fix kantra CI.

:bug: Fix labels validation print

---

cmd/analyze.go
pkg/container/container.go

Closes #220 
basically if you use the host DNS name in a provider settings like:
```
[
{
"name": "aws",
"address": "host.containers.internal:10000",
"initConfig": [
{
"location": "shurley-test",
},
],
},
]
```
notes:
This allows for non-input analysis, which makes sense because location and things must be described in the provider settings. This means we have to turn off the required flag.

:sparkles: adding override provider settings flag

---

README.md
cmd/analyze.go
cmd/settings.go
docs/usage.md
golang.json.sample
java.json.sample

Use provider config options with default configs

---

Dockerfile
Dockerfile.windows
cmd/analyze.go
cmd/settings.go
pkg/container/container.go

This introduces a provider for analyzing .NET application in the cross-platform and windows-only scenarios described in https://github.com/konveyor/enhancements/pull/179.
Hold for #259 , will rebase after that merges.
Fixes #254

:sparkles: kantra support .net provider on windows

---

README.md
cmd/analyze.go
cmd/openrewrite.go
cmd/settings.go
cmd/shimconvert.go
cmd/test.go
docs/developer.md
env.local.sample

This PR changes the environment variable `PODMAN_BIN` to `CONTAINER_TOOL`
as kantra falls back to docker if podman is not present, this variable name makes much more sense.
@dagood Please do have a look and provide any necessary feedback for the same.
Closes #168

:fix :(docs): changed env PODMAN_BIN to CONTAINER_TOOL

---

cmd/analyze.go

Addresses https://issues.redhat.com/browse/MTA-3663

Fix deps in static report bulk option

---

cmd/analyze-bin.go

Missing container-kantra-deps setup caused kantra analyze-bin command failure (details below). Appears when someone skips README step cloning and moving https://github.com/eemcmullan/containerless-kantra-deps.git to `~/.kantra`
Adding check and error message to fail nicely.
Related to: https://github.com/konveyor/kantra/pull/338
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb8c330]
goroutine 1 [running]:
github.com/konveyor-ecosystem/kantra/cmd.(*analyzeBinCommand).walkRuleFilesForLabels.walkRuleSets.func1({0xc0000434c0, 0x1e}, {0x0?, 0x0?}, {0xf049e0, 0xc00026f0b0})
/home/.../go/src/github.com/konveyor/kantra/cmd/util.go:37 +0x30
path/filepath.WalkDir({0xc0000434c0, 0x1e}, 0xc00020fa08) …
```

:bug: Handle missing containerless-deps

---

cmd/analyze.go

Updating CLI message typo for --override-provider-settings.
cc @midays 
Fixes: https://issues.redhat.com/browse/MTA-3424

:bug: Minor analysis help typo fix

---

cmd/analyze-bin.go
cmd/analyze.go

This PR introduces a fix for containerless approach
1) A platform-agnostic approach for copying folder contents from the Kantra home path to the specified output during analysis. It enhances the copy functionality to ensure compatibility across all platforms.
2) Tested on: Windows, Linux

[BUG-FIX]:  Fix issue with 'cp' command not compatible on Windows for containerless analyze

---

cmd/analyze.go

Resolves https://issues.redhat.com/browse/MTA-3668

Cherry-pick #358: Fallback for detecting java projects 

---

cmd/analyze-bin.go
cmd/analyze.go

fixes https://issues.redhat.com/browse/MTA-4160 & https://issues.redhat.com/browse/MTA-4218

Validate mvn and openjdk & fix list providers for containerless mode

---

.github/workflows/testing.yaml
cmd/analyze.go
cmd/settings.go

Fixes https://issues.redhat.com/browse/MTA-4217 and https://issues.redhat.com/browse/MTA-4219

Default to containerless mode

---

cmd/analyze-bin.go

Few missing requirements like Python was producing not helpful messages (like `Failed to validate flags error 90009`) on Windows.
Adding relevant error messages based on debugging containerless kantra on Windows with Igor.
Fixes: https://issues.redhat.com/browse/MTA-4319

:bug: Populate errors for containerless validation flags

---

cmd/analyze.go
cmd/builtin.go
cmd/dotnet.go
cmd/go.go
cmd/java.go
cmd/nodejs.go
cmd/provider.go
cmd/python.go

This PR addresses issue #249. I have modified the `getConfigVolume` method to extract the configuration creation for each provider into an interface implemented by each corresponding struct
Initially, my idea was to place the provider structs in an internal package. However, the `analyzeCommand` does not export any parameters, and I didn't want to change that in this PR since I don't have enough context on the code.
I also considered refactoring other elements, such as separating the `analyzeCommand` itself from the execution context (which is currently also added to `analyzeCommand`). However, I decided not to address this in this PR because I wasn't entirely sure about the scope of the issue
@eemcmullan Should I address what I mention in this PR as well? Is there anything else I'm …

:seedling: Extract getConfigVolumes to an interface

---

.github/workflows/testing.yaml
cmd/analyze-bin.go

This PR is to fix the mentions/ incidents from .m2 folder even though the --analyze-known-libraries flag is not set for java binary analysis.

Container-less Kantra: Update dep label selector to explicitly not scan open-source libraries when analyze-known-libraries is not set

---

cmd/analyze-bin.go

Related to containerless --bulk analysis on Windows. Remove of analysis.log silently failed since it was still opened (which appears on Windows only), moving the file `Close()` from `defer` to just before generating static-report.
If some error occured before reaching the Close, the file should be closed by golang garbage collector.
Fixes: https://issues.redhat.com/browse/MTA-4307

:bug: Close analysis.log before generate static-report

---

cmd/cleanup.go

Summary of changes:
- Removed the condition for windows cleanup additional folders logic
- This is a fix for:  https://github.com/konveyor/kantra/issues/363

[Windows-Only] Container less: Remove condition for windows cleanup additional folders logic

---

cmd/analyze.go

When run `kantra analyze`  to analyze an java app with --bulk and --mode=source-only param, the "dependencies.yaml" won't be genenerate, so when `GenerateStaticReportContainerless` in bulk mode, the [moveResult](https://github.com/konveyor/kantra/blob/main/cmd/analyze-bin.go#L688-L690) will occur an exception due to it try to delete a unexist file, see [here](https://github.com/konveyor/kantra/blob/main/cmd/analyze.go#L1326-L1332). The `kantra analyze` command didn't print an error about it because the error is not handled when call [moveResult](https://github.com/konveyor/kantra/blob/main/cmd/analyze-bin.go#L688-L690).
It should be fixed

fix remove dependencies.yaml file error in bulk mode 

---

cmd/analyze-bin.go

As #444 mentioned, currently, when running kantra CLI command, if multiple rule are processing, then the log will print to the analysis.log, the log in console will not update for a long time. it's better to show to log processing in the console so user can know how many rules has been processed.
Here, use a console hook to print the logs in console
Related PR in analyzer-lsp: https://github.com/konveyor/analyzer-lsp/pull/796
The log looks like:

add rule progress logs

---

pkg/testing/runner.go

See ruleset tests stopping sometimes: https://github.com/konveyor/rulesets/actions/runs/14169025279/job/39693238298?pr=262
A potential cause is resources not being properly cleaned up. This will remove dangling containers.

Cleanup containers after each run

---

README.md

* Added README file extension to fix a 404 when clicking on the setup dev environment link in the main README.md
* Removed blank spaces at the end of the main README.md file
Signed-off-by: Jordi Gil <jgil@redhat.com>

Fix typo in setup dev environment, missing .md extension
